export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';


export const SHOW_WARNING_MESSAGE = 'SHOW_WARNING_MESSAGE';
export const HIDE_WARNING_MESSAGE = 'HIDE_WARNING_MESSAGE';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE';
export const SHOW_SUCCESS_MESSAGE = 'SHOW_SUCCESS_MESSAGE';
export const HIDE_SUCCESS_MESSAGE = 'HIDE_SUCCESS_MESSAGE';

export const SYNC_DATA = 'SYNC_DATA';

export const NETWORK_CONNECTION_AVAILABLE = 'NETWORK_CONNECTION_AVAILABLE';
export const NETWORK_CONNECTION_NOT_AVAILABLE = 'NETWORK_CONNECTION_NOT_AVAILABLE';